### PR TITLE
fix scatterplot y-scale

### PR DESCRIPTION
**Pull request by keckelt**
Hi @NevilleMthw 

A few things I changed:

* in MlProvSidebar, `offlineBoltIcon` was imported multiple times
* You used the _d3_ package, while I used _d3-selection_, which is just a subset. I've therefore removed the d3-seleciton from package.json 

---

For the scatterplot:

* the x-axis title was out of place, as you had
```js
    svg
      .append('text')
      .attr('x', width / 2 + 100)
      .attr('y', height - 15 + 150)
```

The SVG coordinate sytem starts at the top left:
image
source: https://vanseodesign.com/web-design/svg-viewport/

For the x-position, just the half of the width is fine. Would helps me here are the browser dev tools: 
image

With them, I can also update the positon there and check what looks good.

---

The y-axis was simply out of the svg: 
image

The way you specified the chart, the width/height only contain the area enclosed by the axes, while the margin has to contain the axes and their labels.
Threfore, I dind't shift the whole svg by the given margin, but instead created a new plot group that has the marks and axis in it: https://github.com/Vis4Sense/ml-prov-binder/pull/7/files#diff-f7c09868282d8798063d22f5c62933ede4237b286e5f6c1dce44d2e6953f3067R65-R68

But I always find the y-axis a bit tricky and refer to some old code from myself or the internet for that 😉 

---

Some questions:
Is there a reason that some html part defined as constant in the top and others in `addStaticDummyContent`?
* here: https://github.com/Vis4Sense/ml-prov-binder/blob/scatterGraph/src/MlProvSidebar.ts#L12-L17
* and here: https://github.com/Vis4Sense/ml-prov-binder/blob/scatterGraph/src/MlProvSidebar.ts#L46-L55

### CODE REVIEW

**Comment by keckelt** [comment]
I also noticed that the template uses [prettier](https://github.com/prettier/prettier) for code formatting and also checks with GitHub Actions.

I also use it in other projects and find the defaults a good common practice.
You can install the VS Code extension (in case you use VS Code) and it should format the files on save: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode


Otherwise it will also point out all issues in the "files changed" section of PRs: https://github.com/Vis4Sense/ml-prov-binder/pull/4/files

They then get this green check mark on the title:
image

and commits: 
image

**Review by NevilleMthw — COMMENTED** [review]
Hi @keckelt. Thanks for the feedback and changes! Through my understanding, you separated the x and y labels then put the axis, marks and the scatterplot chart as one group. If that's correct?

**Comment by NevilleMthw** [comment]
I use the prettier extension in vscode for other projects as well. But I think the build failed earlier for the previous PR before you made the changes but now I think it should build fine, I've never encountered any failed builds so then I assumed it was prettier extension causing the problem. 
Also, for the HTML part in the ```addStaticDummyContent```, that was done by Rupak. Since I was working on the main graph. I can change it, no problem from my end.

**Comment by keckelt** [comment]
Yes, previously everything was separate: https://github.com/Vis4Sense/ml-prov-binder/pull/4/files#diff-f7c09868282d8798063d22f5c62933ede4237b286e5f6c1dce44d2e6953f3067R21-R44

I grouped the axes and marks and moved them by the margin

**Pull request merged**
